
site:
  server: # each line is a partition, the first is the master site_name:port
    - ["s101:8000", "s201:8001"]
  client: # each line is a partition
    - ["c101"]

process:
  s101: localhost
  s201: p2
  c101: localhost

# process_name - host_addr map
host:
  localhost: 127.0.0.1
  p2: 127.0.0.1
  # localhost: 130.245.173.101
  # p2: 158.130.5.10
  # localhost: 158.130.5.10
  # p2: 130.245.173.101

